# Generated by Django 4.0.4 on 2022-05-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('nlid', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('cost', models.IntegerField()),
                ('msrp', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('upc', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
