# Generated by Django 4.0.4 on 2022-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upc',
        ),
        migrations.AddField(
            model_name='product',
            name='modify',
            field=models.BooleanField(default=False),
        ),
    ]
